### ISSUE TITLE
ValueError: list.remove(x): x not in list

### ISSUE THREAD

**Issue by CharlotteAnne** [philippdre/omniCLIP#17]
Hi

Using omniCLIP on a human dataset, with the following run command:
```
omniCLIP.py --annot \
gencode.v34.primary_assembly.annotation.omniclip.db \
--genome-dir gencode_hg38/chr_sep_files \
--clip-files abcam2_rep1.Aligned.out.sorted.DEDUPLICATED.bam \
--clip-files abcam2_rep2.Aligned.out.sorted.DEDUPLICATED.bam \
--clip-files abcam2_rep3.Aligned.out.sorted.DEDUPLICATED.bam \
--bg-files siControl_rep1.Aligned.out.sorted.DEDUPLICATED.bam \
--bg-files siControl_rep2.Aligned.out.sorted.DEDUPLICATED.bam \
--bg-files siControl_rep3.Aligned.out.sorted.DEDUPLICATED.bam \
--out-dir . \
--rev_strand 0 --seed 12345 --nb-cores 10
```

I get the following error after ~5 hours of run time:
```
setting seed
Loading gene annotation
Loading reads
Parsing the gene annotation
Processing chr1
Processing chr2
Processing chr3
Processing chr4
Processing chr5
Processing chr6
Processing chr7
Processing chr8
Processing chr9
Processing chr10
Processing chr11
Processing chr12
Processing chr13
Processing chr14
Processing chr15
Processing chr16
Processing chr17
Processing chr18
Processing chr19
Processing chr20
Processing chr21
Processing chr22
Processing chrX
Processing chrY
Processing GL000009.2
Processing GL000194.1
Processing GL000195.1
Processing GL000205.2
Processing GL000213.1
Processing GL000216.2
Processing GL000218.1
Processing GL000219.1
Processing GL000220.1
Processing GL000225.1
Processing KI270442.1
Processing KI270711.1
Processing KI270713.1
Processing KI270721.1
Processing KI270726.1
Processing KI270727.1
Processing KI270728.1
Processing KI270731.1
Processing KI270733.1
Processing KI270734.1
Processing KI270744.1
Processing KI270750.1
Saving results
Loading coverage only
Parsing the gene annotation
Processing chr1
Processing chr2
Processing chr3
Processing chr4
Processing chr5
Processing chr6
Processing chr7
Processing chr8
Processing chr9
Processing chr10
Processing chr11
Processing chr12
Processing chr13
Processing chr14
Processing chr15
Processing chr16
Processing chr17
Processing chr18
Processing chr19
Processing chr20
Processing chr21
Processing chr22
Processing chrX
Processing chrY
Processing GL000009.2
Processing GL000194.1
Processing GL000195.1
Processing GL000205.2
Processing GL000213.1
Processing GL000216.2
Processing GL000218.1
Processing GL000219.1
Processing GL000220.1
Processing GL000225.1
Processing KI270442.1
Processing KI270711.1
Processing KI270713.1
Processing KI270721.1
Processing KI270726.1
Processing KI270727.1
Processing KI270728.1
Processing KI270731.1
Processing KI270733.1
Processing KI270734.1
Processing KI270744.1
Processing KI270750.1
Saving results
Masking overlapping positions
Traceback (most recent call last):
  File "/camp/apps/eb/dev/software/omniCLIP/20200702-foss-2020a/omniCLIP.py", line 1014, in <module>
    run_omniCLIP(args)
  File "/camp/apps/eb/dev/software/omniCLIP/20200702-foss-2020a/omniCLIP.py", line 177, in run_omniCLIP
    Sequences = mark_overlapping_positions(Sequences, GeneAnnotation)
  File "/camp/apps/eb/dev/software/omniCLIP/20200702-foss-2020a/omniCLIP.py", line 528, in mark_overlapping_positions
    curr_genes.remove(gene)
ValueError: list.remove(x): x not in list
```

Any idea where this error comes from? Thanks for your help,
Charlotte

**Comment by simojoe** [comment]
Hi Charlotte,

I was not able to exactly recreate your error, but #18 might resolve your issue. Could you apply the PR and rerun the same command to see if this fixes it? You can add the `--use-precomp-CLIP-data` and `--use-precomp-bg-data` options to accelerate the parsing of the BAM files if you kept the .dat files generated by omniCLIP.

Joel
