### ISSUE TITLE
TypeError: 'numpy.float64' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by peaceben** [philippdre/omniCLIP#25]
Hi philippdre,

executing run_omniclip using the parsed background and CLIP files gives me an TypeError (see below). 

But I think i'm probably loosing my way already during the setup process. After following the installation guide i was not able to run omniclip by calling: python3 omniCLIP.py ( ModuleNotFoundError: No module named 'omniCLIP.data_parsing'; 'omniCLIP' is not a package). But i was able to call omniCLIP from my path (in the conda environment). Any thoughts?

Best,
Ben

(omniEnv) linux@linux-Precision-T5600:~/omniCLIP$ omniCLIP run_omniCLIP --db-file ChrC_CLIP --bg-dat CP29A_background --clip-dat CP29A_CLIP --out-dir /home/linux/Desktop/CLIPbam 
Loading gene annotation
Initialising the parameters

Iteration: 0
Computing most likely path
Fitting emission parameters
Fitting emission parameters
Adds pseudo gene to prevent singular matrix during GLM fitting
Estimating expression parameters
Start estimation of expression parameters
Constructing GLM matrix
Estimating expression parameters: GLM matrix constrution
Fitting GLM
Estimating expression parameters: before fitting
Finished expression parameter estimation
Computing sufficient statistic for fitting md
Getting suffcient statistic
Fitting md distribution
Estimating state 0
Estimating state 1
Estimating state 2
Estimating state 3
Fitting transition parameters
Fitting transition parameters
Learning transition model
Iterating over genes
.Traceback (most recent call last):
  File "/home/linux/anaconda3/envs/omniEnv/bin/omniCLIP", line 33, in <module>
    sys.exit(load_entry_point('omniCLIP==0.2.0', 'console_scripts', 'omniCLIP')())
  File "/home/linux/anaconda3/envs/omniEnv/lib/python3.7/site-packages/omniCLIP-0.2.0-py3.7-linux-x86_64.egg/omniCLIP/omniCLIP.py", line 560, in main
    run_omniCLIP(args)
  File "/home/linux/anaconda3/envs/omniEnv/lib/python3.7/site-packages/omniCLIP-0.2.0-py3.7-linux-x86_64.egg/omniCLIP/omniCLIP.py", line 98, in run_omniCLIP
    verbosity=EmissionParameters['verbosity'])
  File "/home/linux/anaconda3/envs/omniEnv/lib/python3.7/site-packages/omniCLIP-0.2.0-py3.7-linux-x86_64.egg/omniCLIP/omniCLIP.py", line 210, in PerformIteration
    verbosity=verbosity)
  File "/home/linux/anaconda3/envs/omniEnv/lib/python3.7/site-packages/omniCLIP-0.2.0-py3.7-linux-x86_64.egg/omniCLIP/omni_stat/trans.py", line 97, in FitTransistionParameters
    verbosity=verbosity)
  File "/home/linux/anaconda3/envs/omniEnv/lib/python3.7/site-packages/omniCLIP-0.2.0-py3.7-linux-x86_64.egg/omniCLIP/omni_stat/trans.py", line 186, in FitTransistionParametersSimple
    for n in range(n_iter):
TypeError: 'numpy.float64' object cannot be interpreted as an integer

**Comment by retrogenomics** [comment]
same problem for me using miniconda3 on macos.
In (omniEnv):
```
$ python3 ~/Lab/bioinfo/tools/omniCLIP/omniCLIP/omniCLIP.py generateDB --gff-file hg38_refGene.gtf --db-file hg38_refGene.db
Traceback (most recent call last):
  File "/Users/gcristof/Lab/bioinfo/tools/omniCLIP/omniCLIP/omniCLIP.py", line 30, in <module>
    from omniCLIP.data_parsing import tools
  File "/Users/gcristof/Lab/bioinfo/tools/omniCLIP/omniCLIP/omniCLIP.py", line 30, in <module>
    from omniCLIP.data_parsing import tools
ModuleNotFoundError: No module named 'omniCLIP.data_parsing'; 'omniCLIP' is not a package
```

**Comment by adomingues** [comment]
I also ran into this issue. Did you find a solution @retrogenomics ?

**Comment by retrogenomics** [comment]
@adomingues no unfortunately...
