### ISSUE TITLE
installation failure

### ISSUE THREAD

**Issue by stasaki** [philippdre/omniCLIP#26]
I ran the following command but it returned an error.

(omniEnv) root@c0560292e992:/var/omniCLIP# python3 setup.py
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied

I modified the command as follows but I still got an error with running the main script. Thank you for your assistance.

(omniEnv) root@c0560292e992:/var/omniCLIP# python3 setup.py install

(omniEnv) root@c0560292e992:/var/omniCLIP# python3 omniCLIP/omniCLIP.py 
Traceback (most recent call last):
  File "omniCLIP/omniCLIP.py", line 33, in <module>
    from omniCLIP.data_parsing import CreateGeneAnnotDB
  File "/var/omniCLIP/omniCLIP/omniCLIP.py", line 33, in <module>
    from omniCLIP.data_parsing import CreateGeneAnnotDB
ModuleNotFoundError: No module named 'omniCLIP.data_parsing'; 'omniCLIP' is not a package

**Comment by adomingues** [comment]
Hi @stasaki, have you solved this problem? I am running into the same issue.

**Comment by adomingues** [comment]
Nevermind. Following your instructions the package is installed system wide, so  this will work:

 ``` 
omniCLIP generateDB --help
```

**Comment by adomingues** [comment]
Also to add that omniCLIP will only run if invoked from inside folder containing the cloned repo which is not super practical.

@philippdre @simojoe would it be possible to make omniCLIP available as conda package? That would make the program much more used.
