### ISSUE TITLE
several bugs in run_omniCLIP

### ISSUE THREAD

**Issue by vagarwal87** [philippdre/omniCLIP#27]
A few bugs for people to be aware of, since the Viterbi can take days and then program terminates unsuccessfully, which can be a bit frustrating:

1) There isn't any description that the db file must end in ".db", so my GeneAnnotation was never set up:

if args.gene_anno_file.split('.')[-1] == 'db':
    GeneAnnotation = gffutils.FeatureDB(args.gene_anno_file, keep_order=True)

I ended up just commenting out the "if" statement and it worked fine. Or you can write in README that it must end in .db

2) I added the following lines:

    if not os.path.exists(EmissionParameters['out_dir']):   <------ added
        os.makedirs(EmissionParameters['out_dir'])           <------ added

    OutFile = os.path.join(EmissionParameters['out_dir'],
                           EmissionParameters['out_file_base'] + '.txt')

because if the output directory doesn't already exist, it would terminate w/ error.

3) --nb-cores > 1 doesn't work for some reason though my hardware has 8 cores...for now just using 1. Possibly this is something weird w/ multiprocessing module & my system, though.

4) it would be helpful in general to describe whether this package is intended for ALL CLIP? I thought so initially, but one of the open comments suggests that you're still evaluating T->C mutations w/ PAR-CLIP. Is it okay to use this with iCLIP/eCLIP/HITS-CLIP or is it always using mutations to evaluate significance?

**Comment by santataRU** [comment]
`run_omniCLIP` terminates unsuccessfully after running for around 15 hours:
(omniEnv) bieniaszlab@pauls-imac-2 omniCLIP % omniCLIP run_omniCLIP --db-file /Users/bieniaszlab/omniCLIP/omniCLIP_gencodev49_db --bg-dat 293T_BG_dat --clip-dat 293T_DDX46_combined_dat --out-dir ./293T_DDX46_combined_peak_calling
Loading gene annotation
Initialising the parameters


Iteration: 0
Computing most likely path
Fitting emission parameters
Fitting emission parameters
Adds pseudo gene to prevent singular matrix during GLM fitting
Estimating expression parameters
Start estimation of expression parameters
Constructing GLM matrix
Estimating expression parameters: GLM matrix constrution
Fitting GLM
Estimating expression parameters: before fitting
Finished expression parameter estimation
Computing sufficient statistic for fitting md
Getting suffcient statistic
Fitting md distribution
Estimating state 0
Estimating state 1
Estimating state 2
Estimating state 3
Fitting transition parameters
Fitting transition parameters
Learning transition model
Iterating over genes
.Computing most likely path
Computing most likely path


Iteration: 1
Fitting emission parameters
Fitting emission parameters
Estimating expression parameters
Start estimation of expression parameters
Constructing GLM matrix
Estimating expression parameters: GLM matrix constrution
Fitting GLM
Estimating expression parameters: before fitting
Finished expression parameter estimation
Computing sufficient statistic for fitting md
Getting suffcient statistic
Fitting md distribution
Estimating state 0
Estimating state 1
Estimating state 2
Estimating state 3
Fitting transition parameters
Fitting transition parameters
Learning transition model
Iterating over genes
.Computing most likely path
Computing most likely path


Iteration: 2
Fitting emission parameters
Fitting emission parameters
Estimating expression parameters
Start estimation of expression parameters
Constructing GLM matrix
Estimating expression parameters: GLM matrix constrution
Fitting GLM
Estimating expression parameters: before fitting
Finished expression parameter estimation
Computing sufficient statistic for fitting md
Getting suffcient statistic
Fitting md distribution
Estimating state 0
Estimating state 1
Estimating state 2
Estimating state 3
Fitting transition parameters
Fitting transition parameters
Learning transition model
Iterating over genes
.Computing most likely path
Computing most likely path


Iteration: 3
Fitting emission parameters
Fitting emission parameters
Estimating expression parameters
Start estimation of expression parameters
Constructing GLM matrix
Estimating expression parameters: GLM matrix constrution
Fitting GLM
Estimating expression parameters: before fitting
Finished expression parameter estimation
Computing sufficient statistic for fitting md
Getting suffcient statistic
Fitting md distribution
Estimating state 0
Estimating state 1
Estimating state 2
Estimating state 3
Fitting transition parameters
Fitting transition parameters
Learning transition model
Iterating over genes
.Computing most likely path
Computing most likely path


Iteration: 4
Fitting emission parameters
Fitting emission parameters
Estimating expression parameters
Start estimation of expression parameters
Constructing GLM matrix
Estimating expression parameters: GLM matrix constrution
Fitting GLM
Estimating expression parameters: before fitting
Finished expression parameter estimation
Computing sufficient statistic for fitting md
Getting suffcient statistic
Fitting md distribution
Estimating state 0
Estimating state 1
Estimating state 2
Estimating state 3
Fitting transition parameters
Fitting transition parameters
Learning transition model
Iterating over genes
.Computing most likely path
Computing most likely path


Iteration: 5
Fitting emission parameters
Fitting emission parameters
Estimating expression parameters
Start estimation of expression parameters
Constructing GLM matrix
Estimating expression parameters: GLM matrix constrution
Fitting GLM
Estimating expression parameters: before fitting
Finished expression parameter estimation
Computing sufficient statistic for fitting md
Getting suffcient statistic
Fitting md distribution
Estimating state 0
Estimating state 1
Estimating state 2
Estimating state 3
Fitting transition parameters
Fitting transition parameters
Learning transition model
Iterating over genes
.Computing most likely path
Computing most likely path


Iteration: 6
Fitting emission parameters
Fitting emission parameters
Estimating expression parameters
Start estimation of expression parameters
Constructing GLM matrix
Estimating expression parameters: GLM matrix constrution
Fitting GLM
Estimating expression parameters: before fitting
Finished expression parameter estimation
Computing sufficient statistic for fitting md
Getting suffcient statistic
Fitting md distribution
Estimating state 0
Estimating state 1
Estimating state 2
Estimating state 3
Fitting transition parameters
Fitting transition parameters
Learning transition model
Iterating over genes
.Computing most likely path
Computing most likely path


Iteration: 7
Fitting emission parameters
Fitting emission parameters
Estimating expression parameters
Start estimation of expression parameters
Constructing GLM matrix
Estimating expression parameters: GLM matrix constrution
Fitting GLM
Estimating expression parameters: before fitting
Finished expression parameter estimation
Computing sufficient statistic for fitting md
Getting suffcient statistic
Fitting md distribution
Estimating state 0
Estimating state 1
Estimating state 2
Estimating state 3
Fitting transition parameters
Fitting transition parameters
Learning transition model
Iterating over genes
.Computing most likely path
Computing most likely path


Iteration: 8
Fitting emission parameters
Fitting emission parameters
Estimating expression parameters
Start estimation of expression parameters
Constructing GLM matrix
Estimating expression parameters: GLM matrix constrution
Fitting GLM
Estimating expression parameters: before fitting
Finished expression parameter estimation
Computing sufficient statistic for fitting md
Getting suffcient statistic
Fitting md distribution
Estimating state 0
Estimating state 1
Estimating state 2
Estimating state 3
Fitting transition parameters
Fitting transition parameters
Learning transition model
Iterating over genes
.Computing most likely path
Computing most likely path


Iteration: 9
Fitting emission parameters
Fitting emission parameters
Estimating expression parameters
Start estimation of expression parameters
Constructing GLM matrix
Estimating expression parameters: GLM matrix constrution
Fitting GLM
Estimating expression parameters: before fitting
Finished expression parameter estimation
Computing sufficient statistic for fitting md
Getting suffcient statistic
Fitting md distribution
Estimating state 0
Estimating state 1
Estimating state 2
Estimating state 3
Fitting transition parameters
Fitting transition parameters
Learning transition model
Iterating over genes
.Computing most likely path
Computing most likely path


Iteration: 10
Fitting emission parameters
Fitting emission parameters
Estimating expression parameters
Start estimation of expression parameters
Constructing GLM matrix
Estimating expression parameters: GLM matrix constrution
Fitting GLM
Estimating expression parameters: before fitting
Finished expression parameter estimation
Computing sufficient statistic for fitting md
Getting suffcient statistic
Fitting md distribution
Estimating state 0
Estimating state 1
Estimating state 2
Estimating state 3
Fitting transition parameters
Fitting transition parameters
Learning transition model
Iterating over genes
.Computing most likely path
Computing most likely path


Iteration: 11
Fitting emission parameters
Fitting emission parameters
Estimating expression parameters
Start estimation of expression parameters
Constructing GLM matrix
Estimating expression parameters: GLM matrix constrution
Fitting GLM
Estimating expression parameters: before fitting
Finished expression parameter estimation
Computing sufficient statistic for fitting md
Getting suffcient statistic
Fitting md distribution
Estimating state 0
Estimating state 1
Estimating state 2
Estimating state 3
Fitting transition parameters
Fitting transition parameters
Learning transition model
Iterating over genes
.Computing most likely path
Computing most likely path


Iteration: 12
Fitting emission parameters
Fitting emission parameters
Estimating expression parameters
Start estimation of expression parameters
Constructing GLM matrix
Estimating expression parameters: GLM matrix constrution
Fitting GLM
Estimating expression parameters: before fitting
Finished expression parameter estimation
Computing sufficient statistic for fitting md
Getting suffcient statistic
Fitting md distribution
Estimating state 0
Estimating state 1
Estimating state 2
Estimating state 3
Fitting transition parameters
Fitting transition parameters
Learning transition model
Iterating over genes
.Computing most likely path
Computing most likely path


Iteration: 13
Fitting emission parameters
Fitting emission parameters
Estimating expression parameters
Start estimation of expression parameters
Constructing GLM matrix
Estimating expression parameters: GLM matrix constrution
Fitting GLM
Estimating expression parameters: before fitting
Finished expression parameter estimation
Computing sufficient statistic for fitting md
Getting suffcient statistic
Fitting md distribution
Estimating state 0
Estimating state 1
Estimating state 2
Estimating state 3
Fitting transition parameters
Fitting transition parameters
Learning transition model
Iterating over genes
.Computing most likely path
Computing most likely path


Iteration: 14
Fitting emission parameters
Fitting emission parameters
Estimating expression parameters
Start estimation of expression parameters
Constructing GLM matrix
Estimating expression parameters: GLM matrix constrution
Fitting GLM
Estimating expression parameters: before fitting
Finished expression parameter estimation
Computing sufficient statistic for fitting md
Getting suffcient statistic
Fitting md distribution
Estimating state 0
Estimating state 1
Estimating state 2
Estimating state 3
Fitting transition parameters
Fitting transition parameters
Learning transition model
Iterating over genes
.Computing most likely path
Computing most likely path


Iteration: 15
Fitting emission parameters
Fitting emission parameters
Estimating expression parameters
Start estimation of expression parameters
Constructing GLM matrix
Estimating expression parameters: GLM matrix constrution
Fitting GLM
Estimating expression parameters: before fitting
Finished expression parameter estimation
Computing sufficient statistic for fitting md
Getting suffcient statistic
Fitting md distribution
Estimating state 0
Estimating state 1
Estimating state 2
Estimating state 3
Fitting transition parameters
Fitting transition parameters
Learning transition model
Iterating over genes
.Computing most likely path
Computing most likely path


Iteration: 16
Fitting emission parameters
Fitting emission parameters
Estimating expression parameters
Start estimation of expression parameters
Constructing GLM matrix
Estimating expression parameters: GLM matrix constrution
Fitting GLM
Estimating expression parameters: before fitting
Finished expression parameter estimation
Computing sufficient statistic for fitting md
Getting suffcient statistic
Fitting md distribution
Estimating state 0
Estimating state 1
Estimating state 2
Estimating state 3
Fitting transition parameters
Fitting transition parameters
Learning transition model
Iterating over genes
.Computing most likely path
Computing most likely path


Iteration: 17
Fitting emission parameters
Fitting emission parameters
Estimating expression parameters
Start estimation of expression parameters
Constructing GLM matrix
Estimating expression parameters: GLM matrix constrution
Fitting GLM
Estimating expression parameters: before fitting
Finished expression parameter estimation
Computing sufficient statistic for fitting md
Getting suffcient statistic
Fitting md distribution
Estimating state 0
Estimating state 1
Estimating state 2
Estimating state 3
Fitting transition parameters
Fitting transition parameters
Learning transition model
Iterating over genes
.Computing most likely path
Computing most likely path


Iteration: 18
Fitting emission parameters
Fitting emission parameters
Estimating expression parameters
Start estimation of expression parameters
Constructing GLM matrix
Estimating expression parameters: GLM matrix constrution
Fitting GLM
Estimating expression parameters: before fitting
Finished expression parameter estimation
Computing sufficient statistic for fitting md
Getting suffcient statistic
Fitting md distribution
Estimating state 0
Estimating state 1
Estimating state 2
Estimating state 3
Fitting transition parameters
Fitting transition parameters
Learning transition model
Iterating over genes
.Computing most likely path
Computing most likely path


Iteration: 19
Fitting emission parameters
Fitting emission parameters
Estimating expression parameters
Start estimation of expression parameters
Constructing GLM matrix
Estimating expression parameters: GLM matrix constrution
Fitting GLM
Estimating expression parameters: before fitting
Finished expression parameter estimation
Computing sufficient statistic for fitting md
Getting suffcient statistic
Fitting md distribution
Estimating state 0
Estimating state 1
Estimating state 2
Estimating state 3
Fitting transition parameters
Fitting transition parameters
Learning transition model
Iterating over genes
.Computing most likely path
Computing most likely path
Maximal number of iterations reached
Finished parameter fitting
Traceback (most recent call last):
  File "/opt/anaconda3/envs/omniEnv/bin/omniCLIP", line 33, in <module>
    sys.exit(load_entry_point('omniCLIP', 'console_scripts', 'omniCLIP')())
  File "/Users/bieniaszlab/omniCLIP/omniCLIP/omniCLIP.py", line 560, in main
    run_omniCLIP(args)
  File "/Users/bieniaszlab/omniCLIP/omniCLIP/omniCLIP.py", line 152, in run_omniCLIP
    Paths, Sequences, Background, IterParameters, GeneAnnotation, OutFile,
UnboundLocalError: local variable 'GeneAnnotation' referenced before assignment
