### ISSUE TITLE
verifying_args is not defined

### ISSUE THREAD

**Issue by kmcoyle** [philippdre/omniCLIP#28]
I am trying to use the run_omniCLIP program but get a Name error:  name 'verifying_args' is not defined. This appears in the ParsingArgs.py file. Commenting out line 44 in ParsingArgs.py bypasses the error.

**Comment by holoenzyme01** [comment]
I think it was a mistake when author update the files. You can delete that argument and run the program without this error.

**Comment by santataRU** [comment]
I have the same problem:
omniCLIP run_omniCLIP --db-file /Users/bieniaszlab/omniCLIP/omniCLIP_gencodev49_db --bg-dat 293T_BG_dat --clip-dat 293T_DDX46_combined_dat --out-dir ./293T_DDX46_combined_peak_calling
Traceback (most recent call last):
  File "/opt/anaconda3/envs/omniEnv/bin/omniCLIP", line 33, in <module>
    sys.exit(load_entry_point('omniCLIP', 'console_scripts', 'omniCLIP')())
  File "/Users/bieniaszlab/omniCLIP/omniCLIP/omniCLIP.py", line 560, in main
    run_omniCLIP(args)
  File "/Users/bieniaszlab/omniCLIP/omniCLIP/omniCLIP.py", line 44, in run_omniCLIP
    EmissionParameters = ParsingArgs.parsing_argparse(args)
  File "/Users/bieniaszlab/omniCLIP/omniCLIP/data_parsing/ParsingArgs.py", line 44, in parsing_argparse
    verifying_args(params)
NameError: name 'verifying_args' is not defined

**Comment by santataRU** [comment]
(omniEnv) bieniaszlab@pauls-imac-2 omniCLIP % cp omniCLIP/data_parsing/ParsingArgs.py omniCLIP/data_parsing/ParsingArgs.py.before_comment_verifying_args.bak

grep -n "verifying_args" omniCLIP/data_parsing/ParsingArgs.py
44:    verifying_args(params)
(omniEnv) bieniaszlab@pauls-imac-2 omniCLIP % python - <<'PY'
from pathlib import Path

p = Path("omniCLIP/data_parsing/ParsingArgs.py")
s = p.read_text()

s = s.replace(
    "    verifying_args(params)\n",
    "    # verifying_args(params)  # commented out: function not defined in source\n",
    1
)

p.write_text(s)
print("Done: commented out verifying_args(params)")
PY
Done: commented out verifying_args(params)

(omniEnv) bieniaszlab@pauls-imac-2 omniCLIP % grep -n "verifying_args" omniCLIP/data_parsing/ParsingArgs.py
44:    # verifying_args(params)  # commented out: function not defined in source
