### ISSUE TITLE
h5py multiprocessing issue

### ISSUE THREAD

**Issue by timlai4** [philippdre/omniCLIP#9]
Running the omniCLIP without setting the number of cores seems to trigger multiple processes calling an opened h5py file. 
```
Traceback (most recent call last):
  File "omniCLIP.py", line 1004, in <module>
    run_omniCLIP(args)
  File "omniCLIP.py", line 351, in run_omniCLIP
    CurrLogLikelihood, IterParameters, First, Paths =
PerformIteration(Sequences, Background, IterParameters, NrOfStates,
First, Paths, verbosity=EmissionParameters['Verbosity'])
  File "omniCLIP.py", line 648, in PerformIteration
    NewEmissionParameters = FitEmissionParameters(Sequences, Background,
NewPaths, EmissionParameters, First, verbosity=verbosity)
  File "omniCLIP.py", line 765, in FitEmissionParameters
    SuffStat = tools.GetSuffStat(Sequences, Background, NewPaths,
NrOfStates, Type='Conv', EmissionParameters=NewEmissionParameters,
verbosity=verbosity)
  File "./data_parsing/tools.py", line 204, in GetSuffStat
    rep = list(Sequences[gene]['Coverage'].keys())[0]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File
"/home/timlai/anaconda3/envs/clip/lib/python3.7/site-packages/h5py/_hl/group.py",
line 264, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: 'Unable to open object (bad object header version number)'
```
Here's the documentation describing this: https://github.com/h5py/h5py/blob/master/examples/multiprocessing_example.py#L17-L21

Indeed by specifically passing --nb-cores 1, this issue is avoided. However, this makes the process extremely slow. My current workaround is to run with multiple cores, hit this issue, then restart the iteration and reads with 1 core.

**Comment by philippdre** [comment]
Can you reproduce this error with the example data?

**Comment by timlai4** [comment]
I have an update on this issue. First, regarding the example data, running without specifying --nb-cores seems to pass through the entire analyses without issues. However, upon specifying --nb-cores to a value greater than 1 (3 in my case), the program hangs on "Constructing GLM matrix". Interrupting the process results in the following traceback:

```
Traceback (most recent call last):
  File "omniCLIP.py", line 1013, in <module>
    run_omniCLIP(args)
  File "omniCLIP.py", line 351, in run_omniCLIP
    CurrLogLikelihood, IterParameters, First, Paths =
PerformIteration(Sequences, Background, IterParameters, NrOfStates,
First, Paths, verbosity=EmissionParameters['Verbosity'])
  File "omniCLIP.py", line 657, in PerformIteration
    NewEmissionParameters = FitEmissionParameters(Sequences, Background,
NewPaths, EmissionParameters, First, verbosity=verbosity)
  File "omniCLIP.py", line 757, in FitEmissionParameters
    NewEmissionParameters =
emission_prob.estimate_expression_param(expr_data, verbosity=verbosity)
  File "./stat/emission_prob.py", line 277, in estimate_expression_param
    A, w, Y, rep = construct_glm_matrix(EmissionParameters, Sequences,
Background, Paths)
  File "./stat/emission_prob.py", line 421, in construct_glm_matrix
    pool.join()
  File
"/home/timlai/anaconda3/envs/clip/lib/python3.7/multiprocessing/pool.py",
line 560, in join
    p.join()
  File
"/home/timlai/anaconda3/envs/clip/lib/python3.7/multiprocessing/process.py",
line 140, in join
    res = self._popen.wait(timeout)
  File
"/home/timlai/anaconda3/envs/clip/lib/python3.7/multiprocessing/popen_fork.py",
line 48, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File
"/home/timlai/anaconda3/envs/clip/lib/python3.7/multiprocessing/popen_fork.py",
line 28, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
```
I have seen this happen a few times with the dataset I was originally working with too. To make matters worse, I encountered different error messages but still related to the h5py issue in several other runs.
